server:
  port: ${PORT:0}
spring:
  application:
    name: booking-service
  data:
    mongodb:
      uri: mongodb+srv://automation:superuser@booking-qdqfh.mongodb.net/service?retryWrites=true&w=majority
      database: service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka