server:
  port: 9291
spring:  application:    name: service-proxy
zuul:
  routes:
    banquet-hall:
      path: /api/v1/banquet-service/**
      service-id: banquet-hall-service
      strip-prefix: false
    booking:
      path: /api/v1/booking-service/**
      service-id: booking-service
      strip-prefix: false
    profile:
      path: /api/v1/auth-service/**
      service-id: profile-service
      strip-prefix: false